USE [FIMS]
GO
/****** Object:  Table [dbo].[SECTION]    Script Date: 11/13/2020 10:22:37 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SECTION](
	[SectionId] [int] NOT NULL,
	[SectionNumber] [nvarchar](20) NOT NULL,
	[SectionDetails] [nvarchar](max) NULL,
	[AcademicYear] [nvarchar](20) NOT NULL,
	[Semester] [nvarchar](20) NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[FacultyCourseId] [int] NOT NULL,
 CONSTRAINT [PK_SECTION] PRIMARY KEY CLUSTERED 
(
	[SectionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DEPARTMENT]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DEPARTMENT](
	[DepartmentId] [int] NOT NULL,
	[DepartmentName] [nvarchar](100) NOT NULL,
	[SchoolId] [int] NULL,
 CONSTRAINT [PK_DEPARTMENT] PRIMARY KEY CLUSTERED 
(
	[DepartmentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EmployeeId] [int] NOT NULL,
	[FirstName] [nvarchar](20) NOT NULL,
	[LastName] [nvarchar](20) NOT NULL,
	[EmailAdress] [nvarchar](30) NOT NULL,
	[PhoneExtension] [int] NOT NULL,
	[IsItPartTime] [bit] NOT NULL,
	[AcceptEmailNotification] [bit] NOT NULL,
	[PositionId] [int] NOT NULL,
	[DepartmentId] [int] NOT NULL,
	[OfficeId] [int] NULL,
 CONSTRAINT [PK_EMPLOYEE] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TEACHER_ASSISTANT]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TEACHER_ASSISTANT](
	[EmployeeId] [int] NOT NULL,
	[TotalCredit] [int] NOT NULL,
	[TotalContactHours] [int] NOT NULL,
 CONSTRAINT [PK_TEACHER_ASSISTANT] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[WORKLOAD]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WORKLOAD](
	[WorkloadId] [int] NOT NULL,
	[Semester] [nvarchar](20) NOT NULL,
	[AcademicYear] [nvarchar](20) NOT NULL,
	[Workload] [int] NOT NULL,
	[LoadType] [nvarchar](20) NOT NULL,
	[IsItApproved] [bit] NOT NULL,
	[EmployeeId] [int] NOT NULL,
 CONSTRAINT [PK_WORKLOAD] PRIMARY KEY CLUSTERED 
(
	[WorkloadId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[TAList]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TAList]
AS
SELECT        dbo.TEACHER_ASSISTANT.EmployeeId, dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.DEPARTMENT.DepartmentName, dbo.SECTION.SectionId, dbo.WORKLOAD.Workload, dbo.WORKLOAD.IsItApproved
FROM            dbo.TEACHER_ASSISTANT INNER JOIN
                         dbo.SECTION ON dbo.TEACHER_ASSISTANT.EmployeeId = dbo.SECTION.EmployeeId INNER JOIN
                         dbo.WORKLOAD ON dbo.TEACHER_ASSISTANT.EmployeeId = dbo.WORKLOAD.EmployeeId INNER JOIN
                         dbo.EMPLOYEE ON dbo.TEACHER_ASSISTANT.EmployeeId = dbo.EMPLOYEE.EmployeeId INNER JOIN
                         dbo.DEPARTMENT ON dbo.EMPLOYEE.DepartmentId = dbo.DEPARTMENT.DepartmentId
GO
/****** Object:  Table [dbo].[FACULTY]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACULTY](
	[EmployeeId] [int] NOT NULL,
	[DateOfBirth] [date] NOT NULL,
	[Nationality] [nvarchar](30) NOT NULL,
	[Status] [nvarchar](10) NOT NULL,
	[MobileNumber] [nvarchar](20) NOT NULL,
	[HighestEducation] [nvarchar](50) NOT NULL,
	[Institution] [nvarchar](50) NOT NULL,
	[Division] [nvarchar](50) NOT NULL,
	[TypeOfContract] [nvarchar](20) NOT NULL,
	[DateNeeded] [date] NOT NULL,
	[RecruitmentStatus] [nvarchar](20) NOT NULL,
	[ApplicationDate] [date] NOT NULL,
	[HiringDate] [date] NULL,
	[Rank] [nvarchar](20) NOT NULL,
	[RequiredLoad] [int] NULL,
	[ConversionRate] [int] NULL,
	[ReleaseDate] [date] NULL,
 CONSTRAINT [PK_FACULTY] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[POSITION]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POSITION](
	[PositionId] [int] NOT NULL,
	[PositionTitle] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_POSITION] PRIMARY KEY CLUSTERED 
(
	[PositionId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SCHOOL]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SCHOOL](
	[SchoolId] [int] NOT NULL,
	[SchoolName] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_SCHOOL] PRIMARY KEY CLUSTERED 
(
	[SchoolId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[Databank]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Databank]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.POSITION.PositionTitle, dbo.EMPLOYEE.IsItPartTime, dbo.SCHOOL.SchoolName, dbo.DEPARTMENT.DepartmentName, dbo.FACULTY.ReleaseDate
FROM            dbo.EMPLOYEE INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId INNER JOIN
                         dbo.POSITION ON dbo.EMPLOYEE.PositionId = dbo.POSITION.PositionId INNER JOIN
                         dbo.DEPARTMENT ON dbo.EMPLOYEE.DepartmentId = dbo.DEPARTMENT.DepartmentId INNER JOIN
                         dbo.SCHOOL ON dbo.DEPARTMENT.SchoolId = dbo.SCHOOL.SchoolId
GO
/****** Object:  View [dbo].[Faculty_Information]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Faculty_Information]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.DEPARTMENT.DepartmentName, dbo.FACULTY.Rank, dbo.WORKLOAD.Workload
FROM            dbo.DEPARTMENT INNER JOIN
                         dbo.EMPLOYEE ON dbo.DEPARTMENT.DepartmentId = dbo.EMPLOYEE.DepartmentId INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId INNER JOIN
                         dbo.WORKLOAD ON dbo.FACULTY.EmployeeId = dbo.WORKLOAD.EmployeeId
GO
/****** Object:  Table [dbo].[COURSE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COURSE](
	[CourseId] [int] NOT NULL,
	[CourseCode] [nvarchar](20) NOT NULL,
	[CourseTitle] [nvarchar](max) NOT NULL,
	[CourseType] [nvarchar](20) NOT NULL,
	[CourseDetails] [nvarchar](max) NULL,
	[CourseCredits] [int] NOT NULL,
	[RequiredContactHours] [int] NOT NULL,
	[DepartmentId] [int] NOT NULL,
 CONSTRAINT [PK_COURSE] PRIMARY KEY CLUSTERED 
(
	[CourseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[TA_Information]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[TA_Information]
AS
SELECT        dbo.TEACHER_ASSISTANT.EmployeeId, dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.SECTION.SectionNumber, dbo.COURSE.CourseTitle
FROM            dbo.TEACHER_ASSISTANT INNER JOIN
                         dbo.SECTION ON dbo.TEACHER_ASSISTANT.EmployeeId = dbo.SECTION.EmployeeId INNER JOIN
                         dbo.EMPLOYEE ON dbo.TEACHER_ASSISTANT.EmployeeId = dbo.EMPLOYEE.EmployeeId CROSS JOIN
                         dbo.COURSE
GO
/****** Object:  View [dbo].[Faculty_JobType]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Faculty_JobType]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.EMPLOYEE.IsItPartTime
FROM            dbo.EMPLOYEE INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId
GO
/****** Object:  Table [dbo].[REQUEST]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUEST](
	[RequestId] [int] NOT NULL,
	[ResourceType] [nvarchar](max) NOT NULL,
	[ResourceQuantity] [int] NOT NULL,
	[Note] [nvarchar](max) NULL,
	[RequestDateTime] [datetime2](7) NOT NULL,
	[DeliveryDateTime] [datetime2](7) NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[OfficeId] [int] NOT NULL,
 CONSTRAINT [PK_REQUEST] PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RESOURCE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RESOURCE](
	[ResourceId] [int] NOT NULL,
	[ResourceName] [nvarchar](max) NOT NULL,
	[OfficeId] [int] NOT NULL,
 CONSTRAINT [PK_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[ResourceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[OFFICE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OFFICE](
	[OfficeId] [int] NOT NULL,
	[OfficeNumber] [nvarchar](10) NOT NULL,
	[OfficeArea] [nvarchar](max) NOT NULL,
	[AvailableResources] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_OFFICE] PRIMARY KEY CLUSTERED 
(
	[OfficeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  View [dbo].[Office_Information]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Office_Information]
AS
SELECT        dbo.OFFICE.OfficeNumber, dbo.OFFICE.AvailableResources, dbo.REQUEST.ResourceType, dbo.REQUEST.DeliveryDateTime
FROM            dbo.OFFICE INNER JOIN
                         dbo.RESOURCE ON dbo.OFFICE.OfficeId = dbo.RESOURCE.OfficeId INNER JOIN
                         dbo.REQUEST ON dbo.OFFICE.OfficeId = dbo.REQUEST.OfficeId
GO
/****** Object:  View [dbo].[Faculty_List]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Faculty_List]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.EMPLOYEE.EmailAdress, dbo.EMPLOYEE.PhoneExtension, dbo.FACULTY.DateOfBirth, dbo.FACULTY.Nationality, dbo.FACULTY.Status, dbo.FACULTY.MobileNumber, 
                         dbo.FACULTY.HighestEducation, dbo.FACULTY.Institution, dbo.FACULTY.Division, dbo.FACULTY.TypeOfContract, dbo.FACULTY.DateNeeded, dbo.FACULTY.RecruitmentStatus, dbo.FACULTY.ApplicationDate, 
                         dbo.FACULTY.HiringDate, dbo.FACULTY.Rank, dbo.FACULTY.RequiredLoad, dbo.FACULTY.ConversionRate, dbo.EMPLOYEE.IsItPartTime
FROM            dbo.EMPLOYEE INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId
GO
/****** Object:  Table [dbo].[CAADU_USER]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CAADU_USER](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_CAADU_USER] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  View [dbo].[Requests_List]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[Requests_List]
AS
SELECT        dbo.OFFICE.OfficeNumber, dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.RESOURCE.ResourceName, dbo.REQUEST.ResourceQuantity, dbo.REQUEST.RequestDateTime, dbo.REQUEST.DeliveryDateTime
FROM            dbo.OFFICE INNER JOIN
                         dbo.REQUEST ON dbo.OFFICE.OfficeId = dbo.REQUEST.OfficeId INNER JOIN
                         dbo.RESOURCE ON dbo.OFFICE.OfficeId = dbo.RESOURCE.OfficeId INNER JOIN
                         dbo.CAADU_USER ON dbo.REQUEST.EmployeeId = dbo.CAADU_USER.EmployeeId INNER JOIN
                         dbo.EMPLOYEE ON dbo.OFFICE.OfficeId = dbo.EMPLOYEE.OfficeId AND dbo.CAADU_USER.EmployeeId = dbo.EMPLOYEE.EmployeeId
GO
/****** Object:  View [dbo].[FacultiesList]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[FacultiesList]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.POSITION.PositionTitle, dbo.EMPLOYEE.IsItPartTime, dbo.SCHOOL.SchoolName, dbo.DEPARTMENT.DepartmentName, dbo.FACULTY.RecruitmentStatus
FROM            dbo.DEPARTMENT INNER JOIN
                         dbo.EMPLOYEE ON dbo.DEPARTMENT.DepartmentId = dbo.EMPLOYEE.DepartmentId INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId INNER JOIN
                         dbo.SCHOOL ON dbo.DEPARTMENT.SchoolId = dbo.SCHOOL.SchoolId INNER JOIN
                         dbo.POSITION ON dbo.EMPLOYEE.PositionId = dbo.POSITION.PositionId
GO
/****** Object:  View [dbo].[OfficesList]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[OfficesList]
AS
SELECT        dbo.OFFICE.OfficeNumber, dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.POSITION.PositionTitle, dbo.EMPLOYEE.IsItPartTime, dbo.OFFICE.AvailableResources
FROM            dbo.EMPLOYEE INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId INNER JOIN
                         dbo.OFFICE ON dbo.EMPLOYEE.OfficeId = dbo.OFFICE.OfficeId INNER JOIN
                         dbo.RESOURCE ON dbo.OFFICE.OfficeId = dbo.RESOURCE.OfficeId INNER JOIN
                         dbo.POSITION ON dbo.EMPLOYEE.PositionId = dbo.POSITION.PositionId
GO
/****** Object:  View [dbo].[WorkloadList]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE VIEW [dbo].[WorkloadList]
AS
SELECT        dbo.EMPLOYEE.FirstName, dbo.EMPLOYEE.LastName, dbo.POSITION.PositionTitle, dbo.EMPLOYEE.IsItPartTime, dbo.DEPARTMENT.DepartmentName, dbo.WORKLOAD.Workload, dbo.WORKLOAD.IsItApproved
FROM            dbo.EMPLOYEE INNER JOIN
                         dbo.FACULTY ON dbo.EMPLOYEE.EmployeeId = dbo.FACULTY.EmployeeId INNER JOIN
                         dbo.POSITION ON dbo.EMPLOYEE.PositionId = dbo.POSITION.PositionId INNER JOIN
                         dbo.DEPARTMENT ON dbo.EMPLOYEE.DepartmentId = dbo.DEPARTMENT.DepartmentId INNER JOIN
                         dbo.WORKLOAD ON dbo.FACULTY.EmployeeId = dbo.WORKLOAD.EmployeeId
GO
/****** Object:  Table [dbo].[FACULTY_COURSE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FACULTY_COURSE](
	[FacultyCourseId] [int] NOT NULL,
	[AcademicYear] [nvarchar](20) NOT NULL,
	[Semester] [nvarchar](20) NOT NULL,
	[CourseTeachingType] [nvarchar](30) NOT NULL,
	[TotalContactHours] [int] NOT NULL,
	[EmployeeId] [int] NOT NULL,
	[CourseId] [int] NOT NULL,
 CONSTRAINT [PK_FACULTY_COURSE] PRIMARY KEY CLUSTERED 
(
	[FacultyCourseId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[GENERATE_NOTIFICATION]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENERATE_NOTIFICATION](
	[NotificationId] [int] NOT NULL,
	[EmployeeId] [int] NOT NULL,
 CONSTRAINT [PK_GENERATE_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[NotificationId] ASC,
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HIRING_DOCUMENTS]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HIRING_DOCUMENTS](
	[DocumentId] [int] NOT NULL,
	[DocumentName] [nvarchar](30) NOT NULL,
	[DocumentFile] [nvarchar](30) NOT NULL,
	[DocumentDate] [date] NOT NULL,
	[DocumentFormat] [nvarchar](10) NOT NULL,
	[EmployeeId] [int] NOT NULL,
 CONSTRAINT [PK_HIRING_DOCUMENTS] PRIMARY KEY CLUSTERED 
(
	[DocumentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[HR_USER]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HR_USER](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_HR_USER] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[INFO_DESK_USER]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[INFO_DESK_USER](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_INFO_DESK_USER] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[IT_USER]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[IT_USER](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_IT_USER] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[MAINTENANCE_USER]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MAINTENANCE_USER](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_MAINTENANCE_USER] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION](
	[NotificationId] [int] NOT NULL,
	[NotificationDateTime] [datetime2](7) NOT NULL,
	[Content] [nvarchar](max) NOT NULL,
	[NotificationTypeId] [int] NOT NULL,
	[WorkloadId] [int] NOT NULL,
	[RequestId] [int] NOT NULL,
 CONSTRAINT [PK_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[NotificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NOTIFICATION_TYPE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NOTIFICATION_TYPE](
	[NotificationTypeId] [int] NOT NULL,
	[Type] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_NOTIFICATION_TYPE] PRIMARY KEY CLUSTERED 
(
	[NotificationTypeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[RECEIVE_NOTIFICATION]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RECEIVE_NOTIFICATION](
	[EmployeeId] [int] NOT NULL,
	[NotificationId] [int] NOT NULL,
 CONSTRAINT [PK_RECEIVE_NOTIFICATION] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC,
	[NotificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[REQUEST_RESOURCE]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[REQUEST_RESOURCE](
	[RequestId] [int] NOT NULL,
	[ResourceId] [int] NOT NULL,
 CONSTRAINT [PK_REQUEST_RESOURCE] PRIMARY KEY CLUSTERED 
(
	[RequestId] ASC,
	[ResourceId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_ADMIN]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_ADMIN](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_SYSTEM_ADMIN] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_ADMIN_ASSISTANT]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_ADMIN_ASSISTANT](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_SYSTEM_ADMIN_ASSISTANT] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_SUPERVISOR]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_SUPERVISOR](
	[EmployeeId] [int] NOT NULL,
	[UserId] [int] NULL,
 CONSTRAINT [PK_SYSTEM_SUPERVISOR] PRIMARY KEY CLUSTERED 
(
	[EmployeeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SYSTEM_USERS]    Script Date: 11/13/2020 10:22:38 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SYSTEM_USERS](
	[UserId] [int] NOT NULL,
	[Username] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](max) NOT NULL,
	[UserType] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_SYSTEM_USERS] PRIMARY KEY CLUSTERED 
(
	[UserId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[CAADU_USER]  WITH CHECK ADD  CONSTRAINT [FK_CAADU_USER_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[CAADU_USER] CHECK CONSTRAINT [FK_CAADU_USER_EMPLOYEE]
GO
ALTER TABLE [dbo].[CAADU_USER]  WITH CHECK ADD  CONSTRAINT [FK_CAADU_USER_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[CAADU_USER] CHECK CONSTRAINT [FK_CAADU_USER_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[COURSE]  WITH CHECK ADD  CONSTRAINT [FK_COURSE_DEPARTMENT] FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[DEPARTMENT] ([DepartmentId])
GO
ALTER TABLE [dbo].[COURSE] CHECK CONSTRAINT [FK_COURSE_DEPARTMENT]
GO
ALTER TABLE [dbo].[DEPARTMENT]  WITH CHECK ADD  CONSTRAINT [FK_DEPARTMENT_SCHOOL] FOREIGN KEY([SchoolId])
REFERENCES [dbo].[SCHOOL] ([SchoolId])
GO
ALTER TABLE [dbo].[DEPARTMENT] CHECK CONSTRAINT [FK_DEPARTMENT_SCHOOL]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_DEPARTMENT] FOREIGN KEY([DepartmentId])
REFERENCES [dbo].[DEPARTMENT] ([DepartmentId])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_DEPARTMENT]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_OFFICE] FOREIGN KEY([OfficeId])
REFERENCES [dbo].[OFFICE] ([OfficeId])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_OFFICE]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_POSITION] FOREIGN KEY([PositionId])
REFERENCES [dbo].[POSITION] ([PositionId])
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_POSITION]
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD  CONSTRAINT [FK_FACULTY_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[FACULTY] CHECK CONSTRAINT [FK_FACULTY_EMPLOYEE]
GO
ALTER TABLE [dbo].[FACULTY_COURSE]  WITH CHECK ADD  CONSTRAINT [FK_FACULTY_COURSE_COURSE] FOREIGN KEY([CourseId])
REFERENCES [dbo].[COURSE] ([CourseId])
GO
ALTER TABLE [dbo].[FACULTY_COURSE] CHECK CONSTRAINT [FK_FACULTY_COURSE_COURSE]
GO
ALTER TABLE [dbo].[FACULTY_COURSE]  WITH CHECK ADD  CONSTRAINT [FK_FACULTY_COURSE_FACULTY] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[FACULTY] ([EmployeeId])
GO
ALTER TABLE [dbo].[FACULTY_COURSE] CHECK CONSTRAINT [FK_FACULTY_COURSE_FACULTY]
GO
ALTER TABLE [dbo].[GENERATE_NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_GENERATE_NOTIFICATION_FACULTY] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[FACULTY] ([EmployeeId])
GO
ALTER TABLE [dbo].[GENERATE_NOTIFICATION] CHECK CONSTRAINT [FK_GENERATE_NOTIFICATION_FACULTY]
GO
ALTER TABLE [dbo].[GENERATE_NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_GENERATE_NOTIFICATION_NOTIFICATION] FOREIGN KEY([NotificationId])
REFERENCES [dbo].[NOTIFICATION] ([NotificationId])
GO
ALTER TABLE [dbo].[GENERATE_NOTIFICATION] CHECK CONSTRAINT [FK_GENERATE_NOTIFICATION_NOTIFICATION]
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS]  WITH CHECK ADD  CONSTRAINT [FK_HIRING_DOCUMENTS_FACULTY] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[FACULTY] ([EmployeeId])
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS] CHECK CONSTRAINT [FK_HIRING_DOCUMENTS_FACULTY]
GO
ALTER TABLE [dbo].[HR_USER]  WITH CHECK ADD  CONSTRAINT [FK_HR_USER_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[HR_USER] CHECK CONSTRAINT [FK_HR_USER_EMPLOYEE]
GO
ALTER TABLE [dbo].[HR_USER]  WITH CHECK ADD  CONSTRAINT [FK_HR_USER_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[HR_USER] CHECK CONSTRAINT [FK_HR_USER_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[INFO_DESK_USER]  WITH CHECK ADD  CONSTRAINT [FK_INFO_DESK_USER_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[INFO_DESK_USER] CHECK CONSTRAINT [FK_INFO_DESK_USER_EMPLOYEE]
GO
ALTER TABLE [dbo].[INFO_DESK_USER]  WITH CHECK ADD  CONSTRAINT [FK_INFO_DESK_USER_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[INFO_DESK_USER] CHECK CONSTRAINT [FK_INFO_DESK_USER_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[IT_USER]  WITH CHECK ADD  CONSTRAINT [FK_IT_USER_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[IT_USER] CHECK CONSTRAINT [FK_IT_USER_EMPLOYEE]
GO
ALTER TABLE [dbo].[IT_USER]  WITH CHECK ADD  CONSTRAINT [FK_IT_USER_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[IT_USER] CHECK CONSTRAINT [FK_IT_USER_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[MAINTENANCE_USER]  WITH CHECK ADD  CONSTRAINT [FK_MAINTENANCE_USER_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[MAINTENANCE_USER] CHECK CONSTRAINT [FK_MAINTENANCE_USER_EMPLOYEE]
GO
ALTER TABLE [dbo].[MAINTENANCE_USER]  WITH CHECK ADD  CONSTRAINT [FK_MAINTENANCE_USER_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[MAINTENANCE_USER] CHECK CONSTRAINT [FK_MAINTENANCE_USER_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIFICATION_NOTIFICATION_TYPE] FOREIGN KEY([NotificationTypeId])
REFERENCES [dbo].[NOTIFICATION_TYPE] ([NotificationTypeId])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIFICATION_NOTIFICATION_TYPE]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIFICATION_REQUEST] FOREIGN KEY([RequestId])
REFERENCES [dbo].[REQUEST] ([RequestId])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIFICATION_REQUEST]
GO
ALTER TABLE [dbo].[NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_NOTIFICATION_WORKLOAD] FOREIGN KEY([WorkloadId])
REFERENCES [dbo].[WORKLOAD] ([WorkloadId])
GO
ALTER TABLE [dbo].[NOTIFICATION] CHECK CONSTRAINT [FK_NOTIFICATION_WORKLOAD]
GO
ALTER TABLE [dbo].[RECEIVE_NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_RECEIVE_NOTIFICATION_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[RECEIVE_NOTIFICATION] CHECK CONSTRAINT [FK_RECEIVE_NOTIFICATION_EMPLOYEE]
GO
ALTER TABLE [dbo].[RECEIVE_NOTIFICATION]  WITH CHECK ADD  CONSTRAINT [FK_RECEIVE_NOTIFICATION_NOTIFICATION] FOREIGN KEY([NotificationId])
REFERENCES [dbo].[NOTIFICATION] ([NotificationId])
GO
ALTER TABLE [dbo].[RECEIVE_NOTIFICATION] CHECK CONSTRAINT [FK_RECEIVE_NOTIFICATION_NOTIFICATION]
GO
ALTER TABLE [dbo].[REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_OFFICE] FOREIGN KEY([OfficeId])
REFERENCES [dbo].[OFFICE] ([OfficeId])
GO
ALTER TABLE [dbo].[REQUEST] CHECK CONSTRAINT [FK_REQUEST_OFFICE]
GO
ALTER TABLE [dbo].[REQUEST]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_SYSTEM_ADMIN] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[SYSTEM_ADMIN] ([EmployeeId])
GO
ALTER TABLE [dbo].[REQUEST] CHECK CONSTRAINT [FK_REQUEST_SYSTEM_ADMIN]
GO
ALTER TABLE [dbo].[REQUEST_RESOURCE]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_RESOURCE_REQUEST] FOREIGN KEY([RequestId])
REFERENCES [dbo].[REQUEST] ([RequestId])
GO
ALTER TABLE [dbo].[REQUEST_RESOURCE] CHECK CONSTRAINT [FK_REQUEST_RESOURCE_REQUEST]
GO
ALTER TABLE [dbo].[REQUEST_RESOURCE]  WITH CHECK ADD  CONSTRAINT [FK_REQUEST_RESOURCE_RESOURCE] FOREIGN KEY([ResourceId])
REFERENCES [dbo].[RESOURCE] ([ResourceId])
GO
ALTER TABLE [dbo].[REQUEST_RESOURCE] CHECK CONSTRAINT [FK_REQUEST_RESOURCE_RESOURCE]
GO
ALTER TABLE [dbo].[RESOURCE]  WITH CHECK ADD  CONSTRAINT [FK_RESOURCE_OFFICE] FOREIGN KEY([OfficeId])
REFERENCES [dbo].[OFFICE] ([OfficeId])
GO
ALTER TABLE [dbo].[RESOURCE] CHECK CONSTRAINT [FK_RESOURCE_OFFICE]
GO
ALTER TABLE [dbo].[SECTION]  WITH CHECK ADD  CONSTRAINT [FK_SECTION_FACULTY_COURSE1] FOREIGN KEY([FacultyCourseId])
REFERENCES [dbo].[FACULTY_COURSE] ([FacultyCourseId])
GO
ALTER TABLE [dbo].[SECTION] CHECK CONSTRAINT [FK_SECTION_FACULTY_COURSE1]
GO
ALTER TABLE [dbo].[SECTION]  WITH CHECK ADD  CONSTRAINT [FK_SECTION_TEACHER_ASSISTANT] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[TEACHER_ASSISTANT] ([EmployeeId])
GO
ALTER TABLE [dbo].[SECTION] CHECK CONSTRAINT [FK_SECTION_TEACHER_ASSISTANT]
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_ADMIN_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN] CHECK CONSTRAINT [FK_SYSTEM_ADMIN_EMPLOYEE]
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_ADMIN_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN] CHECK CONSTRAINT [FK_SYSTEM_ADMIN_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN_ASSISTANT]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_ADMIN_ASSISTANT_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN_ASSISTANT] CHECK CONSTRAINT [FK_SYSTEM_ADMIN_ASSISTANT_EMPLOYEE]
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN_ASSISTANT]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_ADMIN_ASSISTANT_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[SYSTEM_ADMIN_ASSISTANT] CHECK CONSTRAINT [FK_SYSTEM_ADMIN_ASSISTANT_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[SYSTEM_SUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_SUPERVISOR_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[SYSTEM_SUPERVISOR] CHECK CONSTRAINT [FK_SYSTEM_SUPERVISOR_EMPLOYEE]
GO
ALTER TABLE [dbo].[SYSTEM_SUPERVISOR]  WITH CHECK ADD  CONSTRAINT [FK_SYSTEM_SUPERVISOR_SYSTEM_USERS] FOREIGN KEY([UserId])
REFERENCES [dbo].[SYSTEM_USERS] ([UserId])
GO
ALTER TABLE [dbo].[SYSTEM_SUPERVISOR] CHECK CONSTRAINT [FK_SYSTEM_SUPERVISOR_SYSTEM_USERS]
GO
ALTER TABLE [dbo].[TEACHER_ASSISTANT]  WITH CHECK ADD  CONSTRAINT [FK_TEACHER_ASSISTANT_EMPLOYEE] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[EMPLOYEE] ([EmployeeId])
GO
ALTER TABLE [dbo].[TEACHER_ASSISTANT] CHECK CONSTRAINT [FK_TEACHER_ASSISTANT_EMPLOYEE]
GO
ALTER TABLE [dbo].[WORKLOAD]  WITH CHECK ADD  CONSTRAINT [FK_WORKLOAD_FACULTY] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[FACULTY] ([EmployeeId])
GO
ALTER TABLE [dbo].[WORKLOAD] CHECK CONSTRAINT [FK_WORKLOAD_FACULTY]
GO
ALTER TABLE [dbo].[WORKLOAD]  WITH CHECK ADD  CONSTRAINT [FK_WORKLOAD_SYSTEM_SUPERVISOR] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[SYSTEM_SUPERVISOR] ([EmployeeId])
GO
ALTER TABLE [dbo].[WORKLOAD] CHECK CONSTRAINT [FK_WORKLOAD_SYSTEM_SUPERVISOR]
GO
ALTER TABLE [dbo].[WORKLOAD]  WITH CHECK ADD  CONSTRAINT [FK_WORKLOAD_TEACHER_ASSISTANT] FOREIGN KEY([EmployeeId])
REFERENCES [dbo].[TEACHER_ASSISTANT] ([EmployeeId])
GO
ALTER TABLE [dbo].[WORKLOAD] CHECK CONSTRAINT [FK_WORKLOAD_TEACHER_ASSISTANT]
GO
ALTER TABLE [dbo].[EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [CK_EMPLOYEE_EXT] CHECK  (([PhoneExtension] like '[0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[EMPLOYEE] CHECK CONSTRAINT [CK_EMPLOYEE_EXT]
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD  CONSTRAINT [CK_FACULTY_MobileNumber] CHECK  (([MobileNumber] like '00966[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'))
GO
ALTER TABLE [dbo].[FACULTY] CHECK CONSTRAINT [CK_FACULTY_MobileNumber]
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD  CONSTRAINT [CK_FACULTY_Rank] CHECK  (([Rank]='Demonstrator' OR [Rank]='Lecturer' OR [Rank]='Assistant Professor' OR [Rank]='Associate Professor' OR [Rank]='Professor'))
GO
ALTER TABLE [dbo].[FACULTY] CHECK CONSTRAINT [CK_FACULTY_Rank]
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD  CONSTRAINT [CK_FACULTY_Recruitment_Status] CHECK  (([RecruitmentStatus]='Canceled' OR [RecruitmentStatus]='Accepted' OR [RecruitmentStatus]='Pending' OR [RecruitmentStatus]='Rejected'))
GO
ALTER TABLE [dbo].[FACULTY] CHECK CONSTRAINT [CK_FACULTY_Recruitment_Status]
GO
ALTER TABLE [dbo].[FACULTY]  WITH CHECK ADD  CONSTRAINT [CK_FACULTY_Status] CHECK  (([Status]='Single' OR [Status]='Married'))
GO
ALTER TABLE [dbo].[FACULTY] CHECK CONSTRAINT [CK_FACULTY_Status]
GO
ALTER TABLE [dbo].[FACULTY_COURSE]  WITH CHECK ADD  CONSTRAINT [CK_FACULTY_COURSE_Semester] CHECK  (([Semester]='Summer' OR [Semester]='Spring' OR [Semester]='Fall'))
GO
ALTER TABLE [dbo].[FACULTY_COURSE] CHECK CONSTRAINT [CK_FACULTY_COURSE_Semester]
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS]  WITH CHECK ADD  CONSTRAINT [CK_HIRING_DOCUMENTS_Format] CHECK  (([DocumentFormat]='.jpg' OR [DocumentFormat]='.gif' OR [DocumentFormat]='.png' OR [DocumentFormat]='.pdf'))
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS] CHECK CONSTRAINT [CK_HIRING_DOCUMENTS_Format]
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS]  WITH CHECK ADD  CONSTRAINT [CK_HIRING_DOCUMENTS_Name] CHECK  (([DocumentName]='Rrecruitment Requisition form' OR [DocumentName]='Interview Evaluation Form'))
GO
ALTER TABLE [dbo].[HIRING_DOCUMENTS] CHECK CONSTRAINT [CK_HIRING_DOCUMENTS_Name]
GO
ALTER TABLE [dbo].[NOTIFICATION_TYPE]  WITH CHECK ADD  CONSTRAINT [CK_NOTIFICATION_TYPE] CHECK  (([Type]='Calendar notification' OR [Type]='Email notification' OR [Type]='In-app notification'))
GO
ALTER TABLE [dbo].[NOTIFICATION_TYPE] CHECK CONSTRAINT [CK_NOTIFICATION_TYPE]
GO
ALTER TABLE [dbo].[OFFICE]  WITH CHECK ADD  CONSTRAINT [CK_OFFICE_Number] CHECK  (([OfficeNumber] like '[0-3][0-9][0-9]'))
GO
ALTER TABLE [dbo].[OFFICE] CHECK CONSTRAINT [CK_OFFICE_Number]
GO
ALTER TABLE [dbo].[SECTION]  WITH CHECK ADD  CONSTRAINT [CK_SECTION_Semester] CHECK  (([Semester]='Summer' OR [Semester]='Spring' OR [Semester]='Fall'))
GO
ALTER TABLE [dbo].[SECTION] CHECK CONSTRAINT [CK_SECTION_Semester]
GO
ALTER TABLE [dbo].[WORKLOAD]  WITH CHECK ADD  CONSTRAINT [CK_WORKLOAD_LoadType] CHECK  (([LoadType]='Underload' OR [LoadType]='Overload' OR [LoadType]='Normal'))
GO
ALTER TABLE [dbo].[WORKLOAD] CHECK CONSTRAINT [CK_WORKLOAD_LoadType]
GO
ALTER TABLE [dbo].[WORKLOAD]  WITH CHECK ADD  CONSTRAINT [CK_WORKLOAD_Semester] CHECK  (([Semester]='Summer' OR [Semester]='Spring' OR [Semester]='Fall'))
GO
ALTER TABLE [dbo].[WORKLOAD] CHECK CONSTRAINT [CK_WORKLOAD_Semester]
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[13] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 256
            End
            DisplayFlags = 280
            TopColumn = 2
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 294
               Bottom = 136
               Right = 480
            End
            DisplayFlags = 280
            TopColumn = 13
         End
         Begin Table = "POSITION"
            Begin Extent = 
               Top = 6
               Left = 518
               Bottom = 102
               Right = 688
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "SCHOOL"
            Begin Extent = 
               Top = 102
               Left = 518
               Bottom = 198
               Right = 688
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "DEPARTMENT"
            Begin Extent = 
               Top = 138
               Left = 38
               Bottom = 251
               Right = 222
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
     ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Databank'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'    Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Databank'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Databank'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[12] 2[4] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "DEPARTMENT"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 119
               Right = 222
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 260
               Bottom = 136
               Right = 478
            End
            DisplayFlags = 280
            TopColumn = 6
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 516
               Bottom = 136
               Right = 702
            End
            DisplayFlags = 280
            TopColumn = 7
         End
         Begin Table = "SCHOOL"
            Begin Extent = 
               Top = 120
               Left = 38
               Bottom = 216
               Right = 208
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "POSITION"
            Begin Extent = 
               Top = 138
               Left = 246
               Bottom = 234
               Right = 416
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 2505
         Width = 1500
         Width = 3240
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
       ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'FacultiesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'  Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'FacultiesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'FacultiesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "DEPARTMENT"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 119
               Right = 222
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 260
               Bottom = 136
               Right = 478
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 516
               Bottom = 136
               Right = 702
            End
            DisplayFlags = 280
            TopColumn = 10
         End
         Begin Table = "WORKLOAD"
            Begin Extent = 
               Top = 6
               Left = 740
               Bottom = 136
               Right = 910
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 256
            End
            DisplayFlags = 280
            TopColumn = 4
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 294
               Bottom = 136
               Right = 480
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_JobType'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_JobType'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[11] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 246
               Bottom = 136
               Right = 464
            End
            DisplayFlags = 280
            TopColumn = 5
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 502
               Bottom = 136
               Right = 688
            End
            DisplayFlags = 280
            TopColumn = 6
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 21
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_List'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Faculty_List'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "OFFICE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 228
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "RESOURCE"
            Begin Extent = 
               Top = 6
               Left = 266
               Bottom = 119
               Right = 436
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "REQUEST"
            Begin Extent = 
               Top = 6
               Left = 474
               Bottom = 136
               Right = 657
            End
            DisplayFlags = 280
            TopColumn = 2
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Office_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=1 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Office_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[2] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 256
            End
            DisplayFlags = 280
            TopColumn = 3
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 294
               Bottom = 136
               Right = 480
            End
            DisplayFlags = 280
            TopColumn = 13
         End
         Begin Table = "OFFICE"
            Begin Extent = 
               Top = 6
               Left = 518
               Bottom = 136
               Right = 708
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "RESOURCE"
            Begin Extent = 
               Top = 138
               Left = 246
               Bottom = 251
               Right = 416
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "POSITION"
            Begin Extent = 
               Top = 138
               Left = 38
               Bottom = 234
               Right = 208
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 3705
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
        ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'OfficesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N' Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'OfficesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'OfficesList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[8] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "OFFICE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 228
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "REQUEST"
            Begin Extent = 
               Top = 6
               Left = 266
               Bottom = 136
               Right = 449
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "RESOURCE"
            Begin Extent = 
               Top = 6
               Left = 487
               Bottom = 119
               Right = 657
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "CAADU_USER"
            Begin Extent = 
               Top = 6
               Left = 695
               Bottom = 102
               Right = 865
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 120
               Left = 487
               Bottom = 250
               Right = 705
            End
            DisplayFlags = 280
            TopColumn = 3
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
        ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Requests_List'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N' Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Requests_List'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'Requests_List'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[40] 4[20] 2[20] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "COURSE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 248
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "SECTION"
            Begin Extent = 
               Top = 7
               Left = 331
               Bottom = 137
               Right = 505
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "TEACHER_ASSISTANT"
            Begin Extent = 
               Top = 6
               Left = 735
               Bottom = 119
               Right = 924
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 138
               Left = 514
               Bottom = 268
               Right = 732
            End
            DisplayFlags = 280
            TopColumn = 1
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
    ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TA_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'  End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TA_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TA_Information'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[4] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = 0
         Left = 0
      End
      Begin Tables = 
         Begin Table = "TEACHER_ASSISTANT"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 119
               Right = 227
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "DEPARTMENT"
            Begin Extent = 
               Top = 6
               Left = 265
               Bottom = 119
               Right = 449
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "SECTION"
            Begin Extent = 
               Top = 6
               Left = 487
               Bottom = 136
               Right = 661
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "WORKLOAD"
            Begin Extent = 
               Top = 6
               Left = 699
               Bottom = 136
               Right = 869
            End
            DisplayFlags = 280
            TopColumn = 3
         End
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 120
               Left = 38
               Bottom = 250
               Right = 256
            End
            DisplayFlags = 280
            TopColumn = 0
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TAList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'
         Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TAList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'TAList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane1', @value=N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = 
   Begin PaneConfigurations = 
      Begin PaneConfiguration = 0
         NumPanes = 4
         Configuration = "(H (1[41] 4[20] 2[7] 3) )"
      End
      Begin PaneConfiguration = 1
         NumPanes = 3
         Configuration = "(H (1 [50] 4 [25] 3))"
      End
      Begin PaneConfiguration = 2
         NumPanes = 3
         Configuration = "(H (1 [50] 2 [25] 3))"
      End
      Begin PaneConfiguration = 3
         NumPanes = 3
         Configuration = "(H (4 [30] 2 [40] 3))"
      End
      Begin PaneConfiguration = 4
         NumPanes = 2
         Configuration = "(H (1 [56] 3))"
      End
      Begin PaneConfiguration = 5
         NumPanes = 2
         Configuration = "(H (2 [66] 3))"
      End
      Begin PaneConfiguration = 6
         NumPanes = 2
         Configuration = "(H (4 [50] 3))"
      End
      Begin PaneConfiguration = 7
         NumPanes = 1
         Configuration = "(V (3))"
      End
      Begin PaneConfiguration = 8
         NumPanes = 3
         Configuration = "(H (1[56] 4[18] 2) )"
      End
      Begin PaneConfiguration = 9
         NumPanes = 2
         Configuration = "(H (1 [75] 4))"
      End
      Begin PaneConfiguration = 10
         NumPanes = 2
         Configuration = "(H (1[66] 2) )"
      End
      Begin PaneConfiguration = 11
         NumPanes = 2
         Configuration = "(H (4 [60] 2))"
      End
      Begin PaneConfiguration = 12
         NumPanes = 1
         Configuration = "(H (1) )"
      End
      Begin PaneConfiguration = 13
         NumPanes = 1
         Configuration = "(V (4))"
      End
      Begin PaneConfiguration = 14
         NumPanes = 1
         Configuration = "(V (2))"
      End
      ActivePaneConfig = 0
   End
   Begin DiagramPane = 
      Begin Origin = 
         Top = -68
         Left = 0
      End
      Begin Tables = 
         Begin Table = "EMPLOYEE"
            Begin Extent = 
               Top = 6
               Left = 38
               Bottom = 136
               Right = 256
            End
            DisplayFlags = 280
            TopColumn = 3
         End
         Begin Table = "FACULTY"
            Begin Extent = 
               Top = 6
               Left = 294
               Bottom = 136
               Right = 480
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "POSITION"
            Begin Extent = 
               Top = 6
               Left = 518
               Bottom = 102
               Right = 688
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "DEPARTMENT"
            Begin Extent = 
               Top = 102
               Left = 518
               Bottom = 215
               Right = 702
            End
            DisplayFlags = 280
            TopColumn = 0
         End
         Begin Table = "WORKLOAD"
            Begin Extent = 
               Top = 138
               Left = 38
               Bottom = 268
               Right = 208
            End
            DisplayFlags = 280
            TopColumn = 3
         End
      End
   End
   Begin SQLPane = 
   End
   Begin DataPane = 
      Begin ParameterDefaults = ""
      End
      Begin ColumnWidths = 9
         Width = 284
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
         Width = 1500
      End
   End
   Begin CriteriaPane = 
      Begin ColumnWidths = 11
         Column = 1440
         Alias = 900
   ' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'WorkloadList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPane2', @value=N'      Table = 1170
         Output = 720
         Append = 1400
         NewValue = 1170
         SortType = 1350
         SortOrder = 1410
         GroupBy = 1350
         Filter = 1350
         Or = 1350
         Or = 1350
         Or = 1350
      End
   End
End
' , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'WorkloadList'
GO
EXEC sys.sp_addextendedproperty @name=N'MS_DiagramPaneCount', @value=2 , @level0type=N'SCHEMA',@level0name=N'dbo', @level1type=N'VIEW',@level1name=N'WorkloadList'
GO
